// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxDnNl-G2YDWlnJmEpQOYOHb0kSEy66Ho',
    appId: '1:113772128014:web:0106e75f90592a7fc5d95f',
    messagingSenderId: '113772128014',
    projectId: 'washlover-washlover',
    authDomain: 'washlover-washlover.firebaseapp.com',
    storageBucket: 'washlover-washlover.firebasestorage.app',
    measurementId: 'G-C81RNKB78X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcHqdRAvOlJe_vs9d3HQEZ6Dt253dfpd8',
    appId: '1:113772128014:android:0df8663954f4642ac5d95f',
    messagingSenderId: '113772128014',
    projectId: 'washlover-washlover',
    storageBucket: 'washlover-washlover.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYTFS3AxZ1R2MMpxru--vXQkuQ5FcWhrM',
    appId: '1:113772128014:ios:88325841c81ee8b3c5d95f',
    messagingSenderId: '113772128014',
    projectId: 'washlover-washlover',
    storageBucket: 'washlover-washlover.firebasestorage.app',
    iosBundleId: 'com.washlover.washlover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYTFS3AxZ1R2MMpxru--vXQkuQ5FcWhrM',
    appId: '1:113772128014:ios:68643395d8efd653c5d95f',
    messagingSenderId: '113772128014',
    projectId: 'washlover-washlover',
    storageBucket: 'washlover-washlover.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterMapwash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxDnNl-G2YDWlnJmEpQOYOHb0kSEy66Ho',
    appId: '1:113772128014:web:a24073215e2e6993c5d95f',
    messagingSenderId: '113772128014',
    projectId: 'washlover-washlover',
    authDomain: 'washlover-washlover.firebaseapp.com',
    storageBucket: 'washlover-washlover.firebasestorage.app',
    measurementId: 'G-5247WG3XVG',
  );
}
